# Site configuration

# Site title
title: My GitHub Pages Site

# Site description
description: This is my personal GitHub Pages site.

# Base URL
baseurl: ""

# URL
url: "https://arockiaraj1994.github.io/arockiaraj"

# Exclude from processing
exclude:
  - README.md

# Include additional files
include:
  - _pages

# Markdown configuration
markdown: kramdown

# Theme configuration
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
