authors:
  arockiaraj1994:
    name: Arockiaraj Rayappan
    description: Just a simple guy who loves to code.
    avatar: https://avatars.githubusercontent.com/u/18322453?s=400&u=da6963bc8f5c98f710523fdc0e1a589b727f85c0&v=4         # Author avatar
    slug: url           # Author profile slug
    url: https://arockiaraj.co.in/            # Author website URL